modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="babyfat" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Baby Fat" #mandatory
credits="Tazz, Vaky" #optional
authors="Coda, bagu_chan, Team Fusion" #optional
description='''
Baby Fat is a ranchu mod.'''